settings:
  title: 'GeyserMC Status Page'
  url: 'https://geyser-status.rtm516.co.uk' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: site
    name: 'Site'
    url: 'https://geysermc.org/'
    method: GET
    expectStatus: 200
    linkable: true

  - id: api
    name: 'Global API'
    url: 'https://api.geysermc.org/health'
    method: GET
    expectStatus: 204
    linkable: false

  - id: downloads
    name: 'Downloads API'
    url: 'https://download.geysermc.org/'
    method: GET
    expectStatus: 302
    linkable: false
